version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: microservices-ci-cd-backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: microservices-ci-cd-frontend
    depends_on:
      - backend
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: microservices-ci-cd-mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
